version: '3.8'

services:
  backend:
    build: ./server
    ports:
      - '5000:5000'
    environment:
      - MONGO_URI=mongodb://mongo:27017/currencydb
      - REDIS_HOST=redis
    depends_on:
      - mongo
      - redis
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - '3000:80'
    depends_on:
      - backend
    networks:
      - app-network

  mongo:
    image: mongo:5.0
    restart: always
    ports:
      - '27017:27017'
    networks:
      - app-network
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:6.2
    restart: always
    ports:
      - '6379:6379'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
